CREATE DATABASE IF NOT EXISTS ecole;
USE ecole;

CREATE TABLE IF NOT EXISTS classe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(250) NOT NULL,
    prenom VARCHAR(250) NOT NULL,
    photo VARCHAR(250),
    naissance INT NOT NULL
);

